media:
  input: static/images/blogs    # path for images added
  output: /static/images/blogs   # path for images in markdown

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: content
    filename: "{primary}.md"    # filename. dont save with dates and what not
    format: yaml-frontmatter
    fields:
      - name: id
        label: Post ID
        type: uuid
        hidden: true
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: author
        label: Author
        type: string
        default: Admin
      - name: image
        label: Featured Image
        type: image
      - name: date_posted
        label: Date Posted
        type: date
        required: true
      - name: date_modified
        label: Date Modified
        type: date
      - name: tags
        label: Tags
        type: select
        options:
          values: [stories, updates, events, impact]
      - name: body
        label: Post Content
        type: rich-text

settings:
  commit:
    # Uses the logged-in user's name & email for the Git author field
    identity: user
    templates:
      create: "feat(create): add {path}"
      update: "feat(update): update {path}"
      delete: "chore(delete): delete {path}"
      rename: "refactor(rename): move {oldPath} to {newPath}"
